### PR TITLE
Pitch and roll exceptions

### PR DESCRIPTION
**Pull request by BenjaminWantland**
I added two new exceptions for pitch and roll. There is a constant to change the range of the exception.

### CODE REVIEW

**Comment by ClayMav** [comment]
Could not replicate this in the sim, and I hope we never do, @Thomas-McKanna can you think of a good way to validate this works?

**Review by Thomas-McKanna — CHANGES_REQUESTED** [review]
Everything is in place, but this is one big problem: pitch, roll, and yaw are given in radians, not degrees. 

The way I figured this out was by testing the code in my simulator and printing out the pitch and roll values. I noticed they were pretty close to 0 almost all the time and moving only bumped it up to roughly 0.1.

Then I looked at the Mavlink message structure for attitude at https://mavlink.io/en/messages/common.html#ATTITUDE, and there you can see that the units are in radians. All of the data we can get through Dronekit comes from Mavlink messages, so they are typically a good place to check for stuff like this.

Change the constants to radians and I would set the threshold at 0.2 for now (that's double the highest reading I saw in the sim) If it is too low we can always bump it up.

**Comment by BenjaminWantland** [comment]
@Thomas-McKanna 
The constant is set in degrees but it is converted to radians before it checks. I just thought the const would be easier to change if in degrees.

**Comment by Thomas-McKanna** [comment]
A ha! I did not see that. Works for me.

**Review by Thomas-McKanna — DISMISSED** [review]

**Comment by Thomas-McKanna** [comment]
@ClayMav If you want to test it, you could set the threshold to something very low like 2 degrees and see if it triggers then.

**Comment by ClayMav** [comment]
Alright, I am convinced this is alright thanks to Thomas, Can you fix the codacy problems for me, then we can get this finished.

**Review by ClayMav — CHANGES_REQUESTED** [review]
As above

**Review by ClayMav — APPROVED** [review]

**Review by Thomas-McKanna — APPROVED** [review]

**Pull request merged**
